swagger: '2.0'
info:
  title: Library API
  description: A demo api for library app.
  version: 0.0.1

paths:
  /api/author:
    get:
      tags:
        - Author
      summary: All authors
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/author'
    post:
      summary: Create new author
      tags:
        - Author
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/author'
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/resource_id'
        400:
          description: Validation error
  /api/author/{author_id}:
    get:
      summary: Get an author by id
      tags:
        - Author
      parameters:
        - in: path
          name: author_id
          type: integer
          required: true
          minimum: 1
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/author'
        404:
          description: Resource not found
        403:
          description: Validation error
    put:
      summary: Update an author
      tags:
        - Author
      parameters:
        - in: path
          name: author_id
          type: integer
          required: true
          minimum: 1
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/author'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      summary: Remove an author
      tags:
        - Author
      parameters:
        - in: path
          name: author_id
          type: integer
          required: true
          minimum: 1
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error

  /api/publisher:
    get:
      tags:
        - Publisher
      summary: All publishers
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/publisher'
    post:
      summary: Create new publisher
      tags:
        - Publisher
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/publisher'
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/resource_id'
        400:
          description: Validation error
  /api/publisher/{publisher_id}:
    get:
      summary: Get a publisher by id
      tags:
        - Publisher
      parameters:
        - in: path
          name: publisher_id
          type: integer
          required: true
          minimum: 1
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/publisher'
        404:
          description: Resource not found
        403:
          description: Validation error
    put:
      summary: Update a publisher
      tags:
        - Publisher
      parameters:
        - in: path
          name: publisher_id
          type: integer
          required: true
          minimum: 1
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/publisher'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      summary: Remove a publisher
      tags:
        - Publisher
      parameters:
        - in: path
          name: publisher_id
          type: integer
          required: true
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error

  /api/inventory:
    get:
      tags:
        - Inventory
      summary: All book instances in library
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/inventory'
    post:
      tags:
        - Inventory
      summary: Add books to library
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/inventory_bulk'
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/resource_id'
        400:
          description: Validation error
  /api/inventory/{inventory_id}:
    get:
      tags:
        - Inventory
      summary: One book instance
      parameters:
        - in: path
          name: inventory_id
          type: integer
          required: true
          minimum: 1
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/inventory'
    put:
      summary: Update a book instance
      tags:
        - Inventory
      parameters:
        - in: path
          name: inventory_id
          type: integer
          required: true
          minimum: 1
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/inventory'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      summary: Remove a book instance from inventory
      tags:
        - Inventory
      parameters:
        - in: path
          name: inventory_id
          type: integer
          required: true
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error


  /api/book:
    get:
      tags:
        - Book
      summary: Gets all books registred in the system.
      produces:
        - application/json
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/inventory_book'
    post:
      tags:
        - Book
      summary: Create a book
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/book'
      responses:
        200:
          description: Succesful operation
          schema:
            $ref: '#/definitions/resource_id'
        400:
          description: Validation error
          schema:
            type: string
  /api/book/{book_id}:
    get:
      tags:
        - Book
      summary: Return single book by id.
      parameters:
        - in: path
          name: book_id
          type: integer
          required: true
          minimum: 1
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/book'
        404:
          description: Resource not found
        403:
          description: Validation error
    put:
      tags:
        - Book
      summary: Update book
      parameters:
        - in: path
          name: book_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/book'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      tags:
        - Book
      summary: Remove book by id.
      parameters:
        - in: path
          name: book_id
          required: true
          type: integer
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error

  /api/user:
    get:
      tags:
        - User
      summary: Gets all users registred in the system.
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/user_with_id'
    post:
      tags:
        - User
      summary: Create a user
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/user_with_pwd'
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/resource_id'
        403:
          description: Validation error
  /api/user/{user_id}:
    get:
      tags:
        - User
      summary: Return single user by id.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/user_with_id'
        404:
          description: Resource not found
        403:
          description: Validation error
    put:
      tags:
        - User
      summary: Update user
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/user'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      tags:
        - User
      summary: Remove user by id.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error

  /api/user/{user_id}/order:
    get:
      tags:
        - Order
      summary: Get orders made by user.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        200:
          description: Succesfull operation
          schema:
            type: array
            items:
              $ref: '#/definitions/order_with_id'
    post:
      tags:
        - Order
      summary: Create a order for user.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/order'
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/resource_id'
        403:
          description: Validation error
  /api/user/{user_id}/order/{order_id}:
    get:
      tags:
        - Order
      summary: Return single order for user by id.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: path
          name: order_id
          required: true
          type: integer
      responses:
        200:
          description: Succesfull operation
          schema:
            $ref: '#/definitions/order_with_id'
        404:
          description: Resource not found
        403:
          description: Validation error
    put:
      tags:
        - Order
      summary: Update order
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: path
          name: order_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/order'
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error
    delete:
      tags:
        - Order
      summary: Remove order for user by id.
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: path
          name: order_id
          required: true
          type: integer
      responses:
        204:
          description: Succesfull operation
        404:
          description: Resource not found
        403:
          description: Validation error


definitions:
  publisher:
    type: object
    properties:
      title:
        type: string
        minLength: 1
        maxLength: 50
  author:
    type: object
    properties:
      first_name:
        type: string
        minLength: 1
        maxLength: 50
      last_name:
        type: string
        minLength: 1
        maxLength: 50
  book:
    type: object
    properties:
      title:
        type: string
        minLength: 1
        maxLength: 50
      author_id:
        type: integer
        minimum: 1
  inventory:
    type: object
    properties:
      book_id:
        type: integer
        minimum: 1
      publisher_id:
        type: integer
        minimum: 1
      isbn:
        type: string
        pattern: '^\d{3}-\d{1}-\d{2}-\d{6}-\d{1}$'
        example: '978-3-16-148410-0'
      page_number:
        type: integer
        minimum: 1
        maximum: 50000
      edition:
        type: string
        minLength: 1
        maxLength: 50
      year_published:
        type: string
        format: date
        pattern: '^\d{4}$'
        example: '2012'

  inventory_bulk:
    allOf:
      - $ref: '#/definitions/inventory'
      - type: object
        properties:
          amount:
            type: integer
            minimum: 1
            maximum: 100



  inventory_book:
    type: object
    properties:
      book_id:
        type: string
        minLength: 1
        maxLength: 50
      isbn:
        type: string
      publisher_id:
        type: integer
        minimum: 1
      year_published:
        type: string
        format: date
        pattern: '^\d{4}-\d{1,2}-\d{1,2}$'
      amount:
        type: integer
        minimum: 1
        maximum: 500
      page_number:
        type: integer
        minimum: 1
        maximum: 50000

    required:
      - book_id
      - isbn
      - publisher_id
      - year_published
      - amount
  book_or_book_id:
    type: object
    properties:
      book_id:
        type: integer
        format: int64
      book:
        $ref: '#/definitions/book'

  user:
    type: "object"
    properties:
      username:
        type: string
        minLength: 1
        maxLength: 50
      firstName:
        type: string
        minLength: 1
        maxLength: 50
      lastName:
        type: string
        minLength: 1
        maxLength: 50
      email:
        type: string
        minLength: 1
        maxLength: 50
        format: email
        pattern: '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    required:
      - username
      - firstName
      - lastName
      - email
  user_with_id:
    allOf:
      - $ref: '#/definitions/user'
      - type: object
        properties:
          user_id:
            type: "integer"
            format: "int64"
        required:
          - user_id
  user_with_pwd:
    allOf:
      - $ref: '#/definitions/user'
      - type: object
        properties:
          password:
            type: string
            minLength: 8
            maxLength: 100
        required:
          - password
  order:
    type: "object"
    properties:
      inventory_id:
        type: "integer"
        format: "int64"
        minimum: 1
      return_date:
        type: string
        format: date
        pattern: '^\d{4}-\d{1,2}-\d{1,2}$'

    required:
      - inventory_id
      - return_date


  order_with_id:
    allOf:
      - $ref: '#/definitions/order'
      - type: object
        properties:
          order_id:
            type: integer
            format: int64
        required:
          - order_id

  resource_id:
    type: object
    properties:
      id:
        type: integer
    required:
      - id